apiVersion: apps/v1
kind: Deployment
meta: 
  name: NGINX
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80